version: '3.3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # Persist SQLite database outside the container
    
    restart: always
